### ISSUE TITLE
mbx-state-tree support

### ISSUE THREAD

**Issue by joshua1** [IjzerenHein/firestorter#10]
Hi @IjzerenHein , I wanted to ask if it is possible to use this with mobx-state-tree and how

**Comment by IjzerenHein** [comment]
Hi Joshua, I'm going to take a look at this. And suggestions are welcome.

**Comment by IjzerenHein** [comment]
Hi, I've taken a look at this and decided not to pursue this route. MST and Firestorter have a different concept of ownership and I don't see viable merging strategy.

**Comment by agrublev** [comment]
Shame, if only firestorter could create a new model for us to call on :(
