### ISSUE TITLE
ReactNative hotreload error

### ISSUE THREAD

**Issue by rborn** [IjzerenHein/firestorter#102]
Hi, this module is amazing, thanks so much for building it 😻 

I have an issue with hotreload in RN, that from time to time I get an error complaining `initFirestorter` was already called.

Is there a way to avoid this? (you need to basically restart the app)

Thanks 🤗

**Comment by IjzerenHein** [comment]
In order to address that I would recommend checking whether you have called `initFirestorter` already, and don't call it again if you already have

**Comment by rborn** [comment]
@IjzerenHein I managed by patching the module and convert the error in a warning. The hot reload from ReactNative reloads all the code, so `initFirestorter` gets called again and there is not much you can do.
