### ISSUE TITLE
How to declare a query in the Collection options?

### ISSUE THREAD

**Issue by 0x80** [IjzerenHein/firestorter#11]
The docs claim that `query` is part of the options argument of the Collection constructor, but don't mention how to declare it. The only examples I found set the query on the already created collection reference like so:

```
// Create a collection and set a query on it
const col3 = new Collection('artists');
col3.query = col3.ref.orderBy('name', 'asc');
```

How would you pass this query as part of the options?

**Comment by IjzerenHein** [comment]
Hi Thijs. Currently you can pass in a Firestore Query object to the constructor. However, this is a somewhat cumbersome and verbose API and I have therefore not promoted it too much. It works like this:

```js
const query = firebase().firestore().collection('albums').where('name', '>=', 'D');
const col = new Collection('albums', {
  query: query
});
```

I am however currently working on a new Query API which will solve this (amongst other things).
For now, I recommend however to follow the examples in the docs, and initialize the query after the constructor (by using the `ref` of the Collection):

```js
const col = new Collection('albums');
col.query = col.ref.limit(10);
```

**Comment by 0x80** [comment]
Yes, that seems really too verbose. And since you're referencing the album collection twice, it even feels wrong to me.

Wouldn't it be convenient to make the options.query a function which is passed the collection reference? Since that is what the query is built on. Something like this could work I think:

```js
const col = new Collection('albums', {
  query: ref => ref.where('name', '>=', 'D')
});
```

**Comment by IjzerenHein** [comment]
Hey that's actually a really elegant solution, I hadn't considered that one, nice! I'll take it into consideration when I continue work on the Query API.

**Comment by IjzerenHein** [comment]
Hey, I've finished work on the new query API & docs. I've taken your suggestion as I found it very elegant. This is how it will work:
https://github.com/IjzerenHein/firestorter/blob/feature-query-persistency-pagination/docs/Queries.md

Let me know in case you have any feedback on this.

**Comment by 0x80** [comment]
Awesome! That was quick 😄

I don't have any more feedback. It's looking good 👍

**Comment by IjzerenHein** [comment]
Thanks!

**Comment by 0x80** [comment]
Hi @IjzerenHein I was trying out this API today but ran into a problem:

```ts
public pendingUserRegistrations = new Collection("userRegistrations", {
    query: ref =>
      ref
        .where("status", "==", UserRegistrationStatus.PendingApproval)
        .orderBy("updatedAt", "asc")
        .limit(100),
  });
```

Here I am getting an error:

> Cannot read property 'where' of undefined

To solve this I am now doing it the old-school way:

```ts
public pendingUserRegistrations = new FsCollection("userRegistrations");

constructor() {
      const col = this.pendingUserRegistrations;
      col.query = col.ref
        .where("status", "==", UserRegistrationStatus.PendingApproval)
        .orderBy("updatedAt", "asc")
        .limit(100);
  }
```

Could it be that I am missing something?

**Comment by IjzerenHein** [comment]
Hey Thijs. Hmm that's strange, that should have worked. Just so be sure, are you using v0.11 of firestorter?

**Comment by 0x80** [comment]
Somehow my version was still stuck on 0.10. I thought 0.11 would show up in `yarn upgrade-interactive` automatically but it doesn't.

It seems to work now! 👍

**Comment by IjzerenHein** [comment]
Sweet!
