### ISSUE TITLE
Reference a Document by id, passed from one view to another

### ISSUE THREAD

**Issue by ChrisCross3** [IjzerenHein/firestorter#110]
Good evening,
I pass a Document id from one view to another an then want to get access to the Document.

Based on the documentation, I thought I could do this:
`const product = new Document('products/' + props.match.params.id)`

The created object has the right path, but no data.

ATM I do it like this and it works:
`const product = products.docs.find( (doc) => doc.id == props.match.params.id);`

Is this also an appropriate way?

**Comment by IjzerenHein** [comment]
Did you wrap your React component with observer ?
