### ISSUE TITLE
Mobx 6 breaking changes

### ISSUE THREAD

**Issue by kaminskypavel** [IjzerenHein/firestorter#115]
Mobx 6 dropped `decorate()` , there's a long discussion [here ](https://github.com/mobxjs/mobx/issues/2325)

@IjzerenHein are you willing to release a major if ill submit a PR?

**Comment by IjzerenHein** [comment]
@kaminskypavel Definitely!

**Comment by thirdman** [comment]
Just a gentle +1 for this. :D

**Comment by damonmaria** [comment]
Quick attempt at a PR. Tried to change the 2 uses of `decorate()` to `makeObservable()` (inside the constructors) but this breaks 7 tests. Haven't looked any further than that. Will need a detailed look through the breaking changes of Mobx 6.

**Comment by IjzerenHein** [comment]
MobX 6 is now supported! 🤘🤘🤘🤘🤘🤘
https://github.com/IjzerenHein/firestorter/releases/tag/v3.0.0
