### ISSUE TITLE
Error: Attempted import error: 'decorate' is not exported from 'mobx'.

### ISSUE THREAD

**Issue by Codemaine** [IjzerenHein/firestorter#116]

**Comment by IjzerenHein** [comment]
Are you using mobx 6?
https://github.com/IjzerenHein/firestorter/issues/115

**Comment by Codemaine** [comment]
I installed mobs using the code in your documentation

**Comment by IjzerenHein** [comment]
> I installed mobx using the code in your documentation

Is that short for that you don't know? :/

**Comment by Codemaine** [comment]
yes

**Comment by IjzerenHein** [comment]
MobX 6 is now supported! 🤘🤘🤘🤘🤘🤘
https://github.com/IjzerenHein/firestorter/releases/tag/v3.0.0
