### ISSUE TITLE
Under init.ts, the exported makeContext function does not have a type of config param.

### ISSUE THREAD

**Issue by alexandarnikita** [IjzerenHein/firestorter#120]

**Comment by IjzerenHein** [comment]
`makeContext` has been deprecated, use `makeFirestorterContext` instead which does have a type param

**Comment by alexandarnikita** [comment]
@IjzerenHein Even though we are not using ```makeContext``` inside of our application, but we are getting compile failed.
The main reason is ```makeContext``` is export function of this module.
We should remove this deprecated function from the init.ts

**Comment by IjzerenHein** [comment]
Gotcha. You just could have told me in the description you know?

**Comment by alexandarnikita** [comment]
Sorry about that... Later if there is any new issues comes up, I will write down more details in the description.
When are you going to update this issue and release the next version?

**Comment by IjzerenHein** [comment]
I've removed the `makeContext` function and just published a new release:
https://github.com/IjzerenHein/firestorter/releases/tag/v3.0.1
