### ISSUE TITLE
Attempted import error: 'makeObservable' is not exported from 'mobx'.

### ISSUE THREAD

**Issue by nikita-inbev** [IjzerenHein/firestorter#129]
The new version 3.0.1 has another new error
"Attempted import error: 'makeObservable' is not exported from 'mobx'."

![image](https://user-images.githubusercontent.com/76530458/103019355-fa0b3d80-4546-11eb-8b54-fecc4c308115.png)
@IjzerenHein

**Comment by IjzerenHein** [comment]
The new v3 version is compatible with MobX 6. If you want to use MobX 5 or 4, you'll need to stick with the older v2 version.
