### ISSUE TITLE
Cannot find modules

### ISSUE THREAD

**Issue by joshua1** [IjzerenHein/firestorter#13]
I am importing firestorter modules like below 
```
import {
	initFirestorter,
	Collection,
	Document,
	getFirestore
} from 'firestorter'
```
but getting the error 
```
cannot find module initFireStorter in firestorter (same with all the other modules)
```
when i do 
```
import {
	initFirestorter,
	Collection,
	Document,
	getFirestore
} from 'firestorter/src'
```

i get past that error but hit another in init.js where type reference ```initFirestorter(config:any)``` gives an error. what am i missing . I am trying to use this in a next.js app

**Comment by IjzerenHein** [comment]
I have no idea to be honest.

What do you mean by `same with all other modules`:
> cannot find module initFireStorter in firestorter **(same with all the other modules)**

Do you mean you are getting this error on other packages as well?
