### ISSUE TITLE
Remove require()

### ISSUE THREAD

**Issue by aaroniker** [IjzerenHein/firestorter#133]
Really like this package!
But since im using Snowpack it would be great to remove all require() and replace them with import to not mix ESM and CJS code.

Discussion about this: https://github.com/snowpackjs/snowpack/discussions/1321

**Comment by IjzerenHein** [comment]
I guess you are referring to the lodash imports? Correct?

```
const isEqual = require('lodash.isequal');
```

**Comment by aaroniker** [comment]
Correct :)

**Comment by IjzerenHein** [comment]
Alright.

> (I could also open a PR for this)
Yes please :)

**Comment by aaroniker** [comment]
Just did https://github.com/IjzerenHein/firestorter/pull/134

**Comment by IjzerenHein** [comment]
The build tooling has been completely overhauled. There should no longer be any `require` calls in the code. Please upgrade to v4 and let me know in case there are still issues.
https://github.com/IjzerenHein/firestorter/releases/tag/v4.0.0
