### ISSUE TITLE
How to get many documents with specific ids?

### ISSUE THREAD

**Issue by SrBrahma** [IjzerenHein/firestorter#154]
There is the getAll from Firestore and getMany from Typesaurus, but I couldn't find a function in Firestorter to get multiple documents with specific ids. My case is: the User has a doc that contains some stuff ids. I want to get those stuff documents for further info display.

**Comment by IjzerenHein** [comment]
This feature doesn't exist yet in firestorter

**Comment by SrBrahma** [comment]
Thanks!
