### ISSUE TITLE
this.getFirestore is not a function

### ISSUE THREAD

**Issue by wirelessed** [IjzerenHein/firestorter#2]
Hi!

I'm testing your script to use with firestore and when setting a .path, there's some issues:

In my code:
`programme.path = 'docs/' + this.props.doc.id + '/programme';`

An error appeared:

`Uncaught TypeError: this.getFirestore is not a function
    at Collection.set `

I was following your example of using the store.js to store all the collections and documents.

**Comment by IjzerenHein** [comment]
Hi! Oops, that's not right. I've just pushed the fix, thanks for letting me know.

**Comment by wirelessed** [comment]
Hi!

Thanks for the quick response. It seems to work now.

However, I discovered another problem. Whenever I tried to declare an anonymous path in store.js in your example:
`programme: new Collection()`
and I try to change the path `programme.path = ...`
I will get an error:
`Uncaught TypeError: Cannot read property 'id' of undefined
    at Collection.get (VM9620 firestorter.js:838)
    at Collection.set (VM9620 firestorter.js:846)`

However, if I set an initial path to programme, i.e.
`programme: new Collection('/path/')`
It works like a charm.

**Comment by IjzerenHein** [comment]
Ugh, I've clearly not done enough testing here. It's probably a simple fix, I will look into when I have some time.
Thanks for testing!
Cheers

**Comment by IjzerenHein** [comment]
Hi, I've fixed the issue and released it as `v0.6.3`.
Regards, Hein

**Comment by wirelessed** [comment]
Hi!
Thanks for the fix! Works 👍
