### ISSUE TITLE
Feature: Support Mobx strict mode

### ISSUE THREAD

**Issue by msholty-fd** [IjzerenHein/firestorter#22]
Hi! When I enable strict mode via `configure({ enforceActions: true });`, it seems to cause mobx to throw an Error from within this library. Specifically, I think it comes from `Document._onSnapshot` when the `transaction` updates `_fetching` via this line:

```ts
this._fetching.set(false);
```

Is there anything I can do in my usage of firestorter to allow me to enforce actions and also not run into this issue? I am happy to contribute, so if you point out a place in the code that you think we could update something, let me know and I'll submit a PR.

Cheers!

**Comment by IjzerenHein** [comment]
Hi, thanks for the suggestion. I wasn't aware of this `strict` mode in mobx-react. Could you point me to some more documentation on this?

**Comment by msholty-fd** [comment]
https://mobx.js.org/refguide/api.html#-enforceactions-boolean

I think to verify that this works correctly in this library, you just need to `import { configure } from 'mobx'` and then `configure({ enforceActions: true });`. The functions that mutate state will need to have the `@action` decorator or just wrapped with `action()`

**Comment by jonesnc** [comment]
I'm also excited for this! I'd really like to re-enable the `enforceActions` setting.

**Comment by IjzerenHein** [comment]
Alright guys, thanks for letting me know that this is becoming a priority. I've actually run into this one myself. I hope I can work on it soon.

**Comment by IjzerenHein** [comment]
Hi, MobX strict mode is now supported in v1.1.0.
Let me know whether this solves the problem for you.
cheers
