### ISSUE TITLE
Using Document.update without any arguments

### ISSUE THREAD

**Issue by msholty-fd** [IjzerenHein/firestorter#23]
Hello!

When updating a Document right now, I need to do it like so:

```ts
const user = new Document('users/123')
user.update({
  firstName: 'Michael'
});
```

I would like to be able to mutate the Document and then call `update` with no arguments to persist the changes in firebase, like so:

```ts
const user = new Document('users/123')
user.firstName = 'Michael'
user.update()
```

This could be accomplished like so:

```ts
update(fields: any = {}): Promise<void> {
  if (this._schema) {
    // Todo - investigate this deeper
    // Todo - support fieldPath
    this._validateSchema({
      ...this.data,
      ...fields
    });
  }
  if (Object.keys(fields).length > 0) {
    return this._ref.get().update(fields);
  } else {
    return this._ref.get().update(this.data)
  }
}
```

On the other hand, we could create a new method to differentiate the two operations since just updating `fields` is more efficient than sending over all data to be updated, even if it hasn't changed. There could be a `.update` function as well as `updateOnly` where you pass in the specific fields/data to be updated.

**Comment by IjzerenHein** [comment]
Thanks for the suggestion. As of know I consider this functionality as "batching" of updates. A new issue was opened for this #53. Closing thereof.
