### ISSUE TITLE
API suggestion

### ISSUE THREAD

**Issue by andressh** [IjzerenHein/firestorter#29]
Hello

I am new on these technologies so my question may not make much sense.

It would not be possible to make the source of the collections reactive, like in reactive queries, which would allow an integration with react-router?

**Comment by IjzerenHein** [comment]
Yes the source of a Collection is also reactive. You can for instance pass-in a function to `Collection.path` and make that return the path to use. If you access an observable in that function, the function will be automatically re-executed whenever the observable is updated.
