### ISSUE TITLE
Feature - Get all collections from a document?

### ISSUE THREAD

**Issue by wirelessed** [IjzerenHein/firestorter#3]
Hi Hein,

I have nested collections within a document. Is there a function to get all collections from a document?

**Comment by IjzerenHein** [comment]
Hi Colin!

No there isn't yet. It's one of the next features on my list, together with schema-support. I checked the firestore API, but there doesn't seem to be a way to enumerate the collections of a document. So basically, I think this is something that needs to be handled on the client side. I was thinking of making this part of a document schema, in which you can specify data-types and collection references. Not sure how the API will look though.

Do you have any specific requirements or a certain API in mind that I can take into account?

regards, Hein

**Comment by wirelessed** [comment]
Hi Hein

What I'm trying to achieve is to duplicate a document and its subcollections. So I can easily copy the DocumentData, but since there's no way to getSubCollectionsFromDocument, I've to manually specify which collections I know are in the document and then copy their data out in a loop.

**Comment by IjzerenHein** [comment]
Hi Colin, for the last month I pushed quite a few updates, and one of them is the ability to create "smart" path references to other collections and documents. You can then easily combine paths to create the path for a sub-collection. And you can even access document data. I've started documenting this feature, although the docs are not quite finished yet:(https://github.com/IjzerenHein/firestorter/blob/master/docs/PathsAndReferences.md#reactive-paths).

Anyway, I have a proposal for doing sub-collections, and would love to hear your feedback:
https://github.com/IjzerenHein/firestorter/blob/master/docs/SubCollections.md

regards,
Hein

**Comment by wirelessed** [comment]
Hi Hein

This looks great! I will test out when I've time.
Regarding sub-collections, it looks like it will work with my project as well. But you'd definitely still need to know all the possible sub-collection names?

A side question that's not related - Because of how MobX observables work, when i'm running a react function based a user action (e.g. button click), I'm unable to grab the data fields from a document immediately, as the observables only work in the render() function and not in another function? Or correct me if I'm doing this wrongly. 

This is what I mean:
`<button onClick={this.deleteDoc}>Delete</button>`

```
deleteDoc(id) {
     const doc = new Document('artists/' + id);
     // unable to access doc from here as it is created on the fly?
}
```

**Comment by IjzerenHein** [comment]
Hey Colin,

To respond to that question, here is what I would do in that case, where you would have the need to fetch a fresh document:

```js
deleteDoc = async (id) {
     const doc = new Document('artists/' + id);
     await doc.fetch();
     console.log(doc.data);
};
```

or, when you already have a doc, but want to make sure the initial fetch on it has completed:

```js
doSomething = async (doc) {
    // Wait until the doc is ready. A Collection or Document will be ready, once its initial fetch has completed.
     await doc.ready();
     console.log(doc.data);
};
```

**Comment by IjzerenHein** [comment]
Closing, as the original issue is about getting Collections from a document and that is not supported by Firestore API
