### ISSUE TITLE
Set custom SnapshotOptions, especially serverTimestamps option

### ISSUE THREAD

**Issue by Strate** [IjzerenHein/firestorter#30]
Hi!

By default, firestore's `DocumentSnapshot.data()` converts ServerTimestamp tp null. It is possible to override this default behaviour by passing extra option to `DocumentSnapshot.data()`, for example:

```js
snapshot.data({serverTimestamp: "estimate"})
```

But I didn't find a way how to do this in the firestorter. Could you help me with that?

**Comment by Strate** [comment]
Temporary fixed by pathing `data` function:

```js
firebase.firestore.DocumentSnapshot.prototype.data = (function(baseDataFn) {
  return function patchedData(options) {
    if (options == null) {
      options = {
        serverTimestamps: "estimate"
      };
    }
    return baseDataFn.call(this, options);
  };
})(firebase.firestore.DocumentSnapshot.prototype.data);
```

**Comment by IjzerenHein** [comment]
Hi, what do you mean by that it converts the `timestamp` to null? It should return a timestamp right?
Are you using `firestore.settings({ timestampsInSnapshots: true });`?

cheers

**Comment by Strate** [comment]
@IjzerenHein hi, firestore by default converts pending **server**timestamp to null untill it is not loaded from backend, or provided special SnapshotOptions: https://firebase.google.com/docs/reference/js/firebase.firestore.SnapshotOptions

**Comment by IjzerenHein** [comment]
Okay I've just added the option to specify snapshotOptions to Document (on master, not released yet). You can specify the snapshot options like this:

```js
new Document('todos', {
  snapshotOptions: {
    serverTimestamps: 'estimate'
  }
});
```

Would this solve your use case?
cheers

**Comment by IjzerenHein** [comment]
> Okay I've just added the option to specify snapshotOptions to Document (on master, not released yet). You can specify the snapshot options like this:
> 
> ```js
> new Document('todos', {
>   snapshotOptions: {
>     serverTimestamps: 'estimate'
>   }
> });
> ```
> 
> Would this solve your use case?
> cheers

Just released this in official version v1.1.0

**Comment by Strate** [comment]
@IjzerenHein thank you for that, I think collection need support same thing. Or possibility to set something like `Document.defaultSnapshotOptions = {}`

**Comment by IjzerenHein** [comment]
You can already do it by creating a custom document and collection:

```js
class CustomDocument extends Document {
  constructor(source, options = {}) {
    super(source, {
       snapshotOptions: {
         serverTimestamps: 'estimate'
       },
       ...options
    });  
  }
}

class CustomCollection extends Collection {
  constructor(source, options = {}) {
    super(source, {
      createDocument: (source, options) => new CustomDocument(source, options),
      ...options
    });
  }
}
```

**Comment by Strate** [comment]
Great, thank you for that!
