### ISSUE TITLE
Handle onChapshot() errors

### ISSUE THREAD

**Issue by Strate** [IjzerenHein/firestorter#32]
Seems there is no error handling for `.onSnapshot` calls, so errors, like permission deined are missing now.

**Comment by IjzerenHein** [comment]
Hi, I've released a new version which logs a warning for all snapshot errors.
https://github.com/IjzerenHein/firestorter/releases/tag/v0.15.2

Let me know whether this solves your problem.
regards

**Comment by Strate** [comment]
Wow, so fast! Yes, this is definetely solves my problem, thank you so much!

**Comment by RWOverdijk** [comment]
Chapshot 😄 

Logging a warning is a good start f course, but is there a way to set up a handler? In my case it's when permissions get taken away, I need to remove the items from a tree.

I don't mind opening a new issue for this either, I just felt this issue best fit my description.
