### ISSUE TITLE
lodash.isequal should be in dependencies, not in devDependencies

### ISSUE THREAD

**Issue by Strate** [IjzerenHein/firestorter#33]
lodash.isequal should be in dependencies, not in devDependencies

**Comment by IjzerenHein** [comment]
Whoops, you're right. I can imagine that breaks the build on `react-native` projects or when using the new ES modules output.
Just fixed it and pushed a new version:
https://github.com/IjzerenHein/firestorter/releases/tag/v0.15.3

Thanks for reporting

**Comment by Strate** [comment]
@IjzerenHein :+1:
