### ISSUE TITLE
React Native Issue

### ISSUE THREAD

**Issue by teddyteh** [IjzerenHein/firestorter#35]
How exactly do you initialize firestorter with react-native-firebase?

This is what I've tried:
import firebase from 'react-native-firebase';
import {initFirestorter, Collection} from 'firestorter';

initFirestorter({firebase: firebase});

And somehow:
![screenshot_1](https://user-images.githubusercontent.com/8596757/45913301-3553c900-be73-11e8-8dbd-6555ac0d6a15.png)

**Comment by IjzerenHein** [comment]
Hi, it seems you haven't set up `react-native-firebase` on android correctly. This issue has nothing to do with Firestorter itself. Please follow the instructions on `react-native-firebase` on setting it up in your react-native application. I can assure you that Firestorter works perfectly with `react-native-firebase` :)
