### ISSUE TITLE
Query Clauses with Nested Collections

### ISSUE THREAD

**Issue by imikemiller** [IjzerenHein/firestorter#37]
Hi, 

Could you provide some guidance on how to implement the following correctly? If I remove the orderBy clause the nested collection is returned as expected. I assume this is related to my implementation:

```
const Items = observer(class Items extends React.Component{
  ...
  constructor(props){
    super(props);
    this.items = new Collection(`${this.props.list.path}/items`,{
      query: (ref) => ref.orderBy('created_stamp','desc')
    });
  }
...
```

**Comment by IjzerenHein** [comment]
Actually that looks good. What is not working?

**Comment by imikemiller** [comment]
Thanks a lot for getting back. Empty result from the nested collection is
the issue. Without orderBy I get the expected docs from the nested
collection. Can I provide any more information?

**Comment by imikemiller** [comment]
Very possible, in fact I definitely don't. However on a different query on
the parent collection I use the same orderBy and it's cool. also usually
firebase gives a yellow box when it reckons it needs an index. But having
said all that, you make a good shout, I will definitely add an index and
see if it helps.

**Comment by imikemiller** [comment]
OK I have tested the indexing and no joy. As I thought its not required as I have only a single field clause.

    Error: HTTP Error: 400, this index is not necessary, single field indexes are built in

If I log the state of the result in my render function it looks correct its just empty:

    Proxy {length: 0, Symbol(mobx administration): ObservableArrayAdministration}
      [[Handler]]: Object
      [[Target]]: Array(0)
      [[IsRevoked]]: false

**Comment by IjzerenHein** [comment]
Hmm this is a weird one. I know adding the index was a long shot, but was worth a try. So you say that the `orderBy` works on a different global collection, which seems to indicate the code for it seems to work.

Could you try enabling the `debug` flag on the Collection and send me the logs?

```js
new Collection(mypath, {query: ..., debug: true});
```

The next thing I would try to verify whether the problem is with Firestore itself or in Firestorter. E.g. to quickly define a query using the Firebase API, like this:

```js
firebase.firestore().collection('mycol').doc('mydoc').collection('subcol').orderBy('created_stamp', 'desc').onSnapshot((snapshot) => {
  console.log('onSnapshot, docs.length: ', snapshot.docs.length);
});
```

**Comment by IjzerenHein** [comment]
Alright appreciate it man. Glad the problem is resolved. If it re-appears just drop a note here and we'll have a closer at it.
Cheers, Hein

**Comment by imikemiller** [comment]
You're a legend cheers

**Comment by imikemiller** [comment]
OK so by moving the query inside the componentWillRecieveProps function I got it to work. Thanks a lot.. again!

```
componentWillReceiveProps (newProps) {
    if (newProps.list !== this.props.list) {
      this.items = new Collection(`${newProps.list.path}/items`, {
        query:(ref)=>{ return ref.orderBy('created_stamp','desc')}
      });
    }
  }
```
