### ISSUE TITLE
Document.update.test.js is failing

### ISSUE THREAD

**Issue by imikemiller** [IjzerenHein/firestorter#39]
Specific failing tests are `update field with schema` and `update field-path with schema`. It appears the issue is that the update is rejected if mandatory fields from the schema are missing. I am not sure the intent here but seems that the schema should only validate fields contained in the update (different behavior from add/set which would need to enforce the mandatory rules)

`npm test -- -t 'update field'`

![screenshot from 2018-09-28 10-27-12](https://user-images.githubusercontent.com/24856374/46197119-1f2d8900-c309-11e8-9087-d1c4069ecdea.png)

**Comment by IjzerenHein** [comment]
Hi, there is an issue with the tests at the moment. It seems someone deleted the test data from Firebase (which was still open) and that is now causing the tests to fail. It's on my radar and I've planned to fix this next week.

**Comment by imikemiller** [comment]
Ahh I see. I made PR which includes some seeds scattered about. If the data is supposed to be there from the top I can move these into the init.js file. I will close this
