### ISSUE TITLE
Add `hasData` observable property for Document

### ISSUE THREAD

**Issue by Strate** [IjzerenHein/firestorter#41]
Hey! It would be useful to have `hasData: boolean` property on Document. It behaves as:

1. When Document have no data, it resolves to `false`

2. When Document have any data available, it resolves to `true`.

It is not same as existing `isLoading`, because it is not become `false` when new ref set, for example.

**Comment by IjzerenHein** [comment]
Hey Artur, yes this is a really good idea. I will add it in the next release which I'm working on right now. Cheers

**Comment by IjzerenHein** [comment]
I've added `hasData`, it's in the just released v1.1.0 release.
cheers
