### ISSUE TITLE
Handle Documents in Store

### ISSUE THREAD

**Issue by MichZipp** [IjzerenHein/firestorter#44]
Hi, 

I'm a beginner with react and firebase! I would like to have the current User in the store to access the data from different components. If I use the following Code, the currentUser Document is always empty. The "setCurrentUser" function is called, when a user has logged in. If I query the whole user collection with the user id, it works fine. But I think it would be more effitient to directly access the document. 

``` javascript
class User extends Document {
    constructor(source, options) {
		super(source, {
			...(options || {}),
			schema: struct({
				firstname: "string",
                lastname: "string",
                email: "string"
			})
		});
    }
}

var users = new Collection("users", {
    DocumentClass: User
});

var currentUser = new Document();

function setCurrentUser(uid) {
    currentUser = new Document("users/" + uid, {
        DocumentClass: User
    });
} 
  
export {
    users,
    currentUser,
    setCurrentUser
}
```

Greetings,
Michael

**Comment by IjzerenHein** [comment]
Hi Michael. What about:

```js
...
var currentUser = new Document();

function setCurrentUser(uid) {
    currentUser.path = "users/" + uid;
}
...
```
I think that will work.

regards, Hein

**Comment by MichZipp** [comment]
That's it, Thanks!

**Comment by gregoryanm** [comment]
Where did you place this in your code, I am placing it on the auth state changed, and nothing so far
