### ISSUE TITLE
Unable to set Document path directly with new Document()

### ISSUE THREAD

**Issue by wirelessed** [IjzerenHein/firestorter#5]
Hi
I think the `new Document()` function is not working correctly.
When I try
`const myDoc = new Document("users/" + userid + "/docs/" + docid);`

This error appears:
`Uncaught (in promise) Error: Invalid collection reference. Collection references must have an odd number of segments, but <myfilename> has 4`

However, when I try the following, it works perfectly.
`const myDoc = new Document();`
`myDoc.path = "users/" + userid + "/docs/" + docid;`

**Comment by IjzerenHein** [comment]
Huh, that is weird indeed. I'm gonna have a look whether I can reproduce it 👍

**Comment by IjzerenHein** [comment]
Hi, after inspection I'm pretty sure this issue has already been fixed. It is fixed in v0.8.1, please upgrade to the latest version.

**Comment by wirelessed** [comment]
great! thank you!
