### ISSUE TITLE
Can't import Mode from Types.d.ts

### ISSUE THREAD

**Issue by damonmaria** [IjzerenHein/firestorter#55]
I'm trying to use the new Typescript features in a create-react-app (using react-scripts-ts) based project. 

I can perform some imports from `firestorter/lib/Types`, example: `import { DocumentSource, IDocumentOptions } from 'firestorter/lib/Types'` works fine.

But if I try to provide the `mode` in the `Collection` constructor options then importing `Mode` from `firestorter/lib/Types` fails to compile. 

```typescript
import { Mode } from 'firestorter/lib/Types'
const sites = new Collection('sites', { mode: Mode.On })
```

results in:
```Module not found: Can't resolve 'firestorter/lib/Types' in '/Users/damon/development/mindhive/autoflocc/cloud/firebase/client/src/store'```

This seems like I've got something wrong. How do I use mode with Typescript?

**Comment by IjzerenHein** [comment]
Not exactly sure what's going on there. Nevertheless, I've added `Mode` as a regular export, so it can also be used with plain JavaScript. This also fixed the TypeScript problem. You can now import it directly like this with TypeScript `import { Mode } from 'firestorter';`
Released as https://github.com/IjzerenHein/firestorter/releases/tag/v1.1.1
cheers
