### ISSUE TITLE
Custom document ID's

### ISSUE THREAD

**Issue by cworf** [IjzerenHein/firestorter#6]
Hey,
A feature I used in a recent angular project while using the angularFire library was the ability to give a document a custom id instead of using the default format. That would be a really useful feature for this. Correct me if I somehow missed it in the docs. Thanks! Great work!

**Comment by IjzerenHein** [comment]
Hi, you can do this already. Please check:
https://github.com/IjzerenHein/firestorter/blob/master/docs/AddUpdateDelete.md

Alternatively, you can use the Document interface to create documents with custom IDs:
```js
const todo = new Document('todos/mydoc');

// Use .set to create the document in the back-end
todo.set({
	finished: false,
	text: 'this is awesome'
});
```

**Comment by cworf** [comment]
ah jeez sorry about that. Thats great thank you!
