### ISSUE TITLE
Input Fields not Changing After Update

### ISSUE THREAD

**Issue by gregoryanm** [IjzerenHein/firestorter#61]
Hello, I have some input fields on a component where once the value changes and I move on to the next document, the input field that was changed will not render new data.  It only changes the data on the fields  that have not had any edits.  I tested one scenario if I make a change, and lets say I change the field on the backend it works.  I assume I am bugging it out and should really use a modal or something?  Everything is resolved once I refresh the browser or move on to another area. Just as long as the fields are refreshed.

**Comment by IjzerenHein** [comment]
Are you seeing any warnings in the console? Is it possible that the Input component you are using is a controlled component and therefore doesn't update?

**Comment by gregoryanm** [comment]
Jeez, bad move on my part, your tool was getting me excited so I was copying and pasting a alot of crap over...  there it is defaultvalue...  Thanks very much, and awesome tool!!!

**Comment by IjzerenHein** [comment]
Awesome, glad it works now :)
