### ISSUE TITLE
Typescript: fetch() should use Document generic

### ISSUE THREAD

**Issue by damonmaria** [IjzerenHein/firestorter#64]
In `Document`: `public async fetch(): Promise<Document>` should use `Document<T>`

**Comment by IjzerenHein** [comment]
Hi! I'm noticing that I have too little time and need some help maintaining this repo. Would you be interested in being a collaborator?
cheers, Hein

**Comment by damonmaria** [comment]
I don't have a huge amount of time but Firestorter is a valuable package for us, and pretty awesome in general. Also know that while having dozens of private (company) repos I haven't worked as a collaborator on an open source repo before. But yes, I'm happy to work on this. 

As an easy first step I could do a PR for this issue?

**Comment by IjzerenHein** [comment]
Yes that would be awesome Damon!

**Comment by damonmaria** [comment]
PR: #66

**Comment by IjzerenHein** [comment]
Thanks Damon, I've just released this fix as https://github.com/IjzerenHein/firestorter/releases/tag/v1.2.1
cheers, Hein
