### ISSUE TITLE
Cant seem to get docs from nested collection

### ISSUE THREAD

**Issue by cworf** [IjzerenHein/firestorter#7]
I am having an issue with getting the array of existing docs from a nested collection, below is my code (simplified considerably from the original to just show the related problem):
```jsx
import React, { Component } from 'react';
import {observer} from 'mobx-react';
import { Collection } from 'firestorter';

class EventInventoryTable extends Component {

  render(){
    const { classes, eventDoc, category } = this.props;
    const eventOrdersCol = new Collection( () => `${eventDoc.path}/orders)`; 
    return (
        <Table className={classes.table}>
          <TableBody>
            {console.log(eventOrdersCol.docs) //returns large array of undefined objects}  
          {eventOrdersCol.docs.map(orderRefDoc => {
            console.log(orderRefDoc); //loop didnt run so this never fires.
          })}
          </TableBody>
        </Table>
    );
  }
}


export default observer(withStyles(styles)(EventInventoryTable));
```

I have followed your documentation for creating path references, reactive paths, ive even tried hard-coding a collection/documentID/collection path that I know for certain contains three documents, and each time the `console.log(eventOrdersCol.docs)` comes up empty

```jsx
const eventOrdersColRef = new Collection(
    	firebase  //<---- btw this is written as "firebase()" in the docs, but only works without the parentheses
    		.firestore()
    		.collection(`${eventDoc.path}/orders`)
      );
    console.log(eventOrdersColRef.ref); //returns a collection reference!! yay?!
    const eventOrdersCol = new Collection(eventOrdersColRef.ref); 
    console.log(eventOrdersCol.docs); //nope :(
```
this snippet's first console log returns a collection reference that contains the correct path and everything!
but when I try to get the docs I know exist in said collection, the resulting array is full of 999 undefined objects.

I have tried everything I can think of, im sure im doing it wrong because nobody has mentioned this in here before. so perhaps I am reading the docs wrong. Im relatively new to coding so hopefully you can help me out on this road block.

Thank you so much!

**Comment by IjzerenHein** [comment]
Hi Colin. I'm pretty sure the problem lies in the fact that you create a new Collection every time the `render` function is executed. The data is then fetched (asynchronously) and when available, the `render` function is called. But because it then creates a new Collection, you have no way of accessing the previously fetched collection.

I suggest creating the Collection in the constructor, and setting the reference/path of it in both the constructor and in `componentWillReceiveProps` in case a new document is received.

**Comment by cworf** [comment]
thanks for getting back so quickly! I tried the following, but still returns array of undefined objects for docs.

```jsx
class EventInventoryTable extends Component {

  constructor(props){
    super(props)
    this.eventOrdersColRef = new Collection(
    	firebase  //<---- btw this is written as "firebase()" in the docs, but only works without the parentheses
    		.firestore()
    		.collection(`${this.props.eventDoc.path}/orders`)
      );
  }

  componentWillReceiveProps(newProps) {
    this.eventOrdersColRef = new Collection(
    	firebase  //<---- btw this is written as "firebase()" in the docs, but only works without the parentheses
    		.firestore()
    		.collection(`${this.props.eventDoc.path}/orders`)
      );
  }

  render(){
...
...
...
{console.log(this.eventOrdersColRef.ref)}
```

`console.log(this.eventOrdersColRef.ref)` returns an object  that looks like the following:
```javascript
{
firestore : Firestore {_queue: AsyncQueue, INTERNAL: {…}, _config: FirestoreConfig, _databaseId: DatabaseId, _dataConverter: UserDataConverter, …},
id : "orders",
parent : DocumentReference,
path : "events/XFwkG73DoTFGs9baU456/orders",
_query : Query {path: ResourcePath, explicitOrderBy: Array(0), filters: Array(0), limit: null, startAt: null, …},
 __proto__ : Query
```

the path is proper and has docs in it. but im not sure how to pull them out of this reference.

**Comment by IjzerenHein** [comment]
I don't quite understand what's going on, but lets try to do this properly and see what the result is. This is how I would define a Collection in a Component and update its path accordingly when the `eventDoc` prop changes.

```js
class EventInventoryTable extends Component {
  constructor(props){
    super(props);
    this.eventOrdersColRef = new Collection(`${props.eventDoc.path}/orders`);
  }

  componentWillReceiveProps(newProps) {
    if (newProps.eventDoc !== this.props.eventDoc) {
      this.eventOrdersColRef.path = `${newProps.eventDoc.path}/orders`;
    }
  }

  render() {
    const {fetching, docs} = this.eventOrdersColRef;
    console.log('fetching: ', fetching, ', docs: ', docs);
    return null;
  }
}

export default observer(withStyles(styles)(EventInventoryTable));
```

Could you let me know what this outputs on the console?

**Comment by cworf** [comment]
the console outputs:
fetching: false
docs: ObservableArray (containing the same 999 undefined objects)

**Comment by IjzerenHein** [comment]
This is what I would expect on the first call to render. However, there should be additional calls to render, indicating that it is fetching, and once done fetching, the docs prop should contain the result.

It almost seems like the Collection is not being observed correctly.
Are you sure you've wrapped the component correctly with `observer`?

**Comment by cworf** [comment]
ok yeah I was wrapping the export statement with the observer but after I wrapped the whole class in it, the resulting output is still fetching: false, HOWEVER, there are now three docs being returned! perhaps my console is just not catching the true value because clearly they are being fetched now. Thanks for your help!! I have another layer to jump down and ill report back whether or not it worked.

I really appreciate it, is there any way I can send a tip to donate to this project?

**Comment by cworf** [comment]
It worked! 
The document referenced another document in a different collection and I had to render that, so I had to create an additional component to pass the doc reference into via props. I guess the moral of the story is that no matter what, the references must be used in a constructor. thanks again!

**Comment by IjzerenHein** [comment]
Alright, great to hear you've managed to fix the problem!
I'm not sure what you mean that the references must be used in the constructor though 🤔

And I really appreciate that would want to give a small donation for the project. I'm going to set that up with a link on the main README, and get back to you on that.

cheers!

**Comment by IjzerenHein** [comment]
Hi, I've added a donate link:
https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=C7KAZKHW6MXYL

Cheers!

**Comment by cworf** [comment]
> I'm not sure what you mean that the references must be used in the constructor though 🤔

Im talking about the document or  collection reference `const doc = new Document( ${documentPath} )` needing to be used in the class constructor instead of inside the render method.

**Comment by IjzerenHein** [comment]
Right I see. Yes, the data needs to be fetches from firebase back-end, and therefore you cannot just create Collections or Documents in the render method and expect them to have data. You'll need to either store the data in a store or create the Document/Collection and add it to the state/members of the Component. When rendered, Firstorter will then start fetching the data. And because of the observer, the Component will then be re-rendered when the data is available.

**Comment by cworf** [comment]
I am now experiencing another issue which was not immediately apparent. but to be honest this one seems kinda buggy. I am doing everything as we have discussed in this thread, sending a component a document path as a prop, calling the new document path in the class constructor, and displaying document fields in the render method. I even included your snippet for the componentWillRecieveProps method. I am able to display any data in the first level of the document, but as soon as I try to go any further into a nested object I get an error. 

for example in this document (note: this is all fake data):
```javascript
  {
    "address": "898 Matthews Court, Fairlee, South Carolina, 2084",
    "phone": "+1 (905) 419-2467",
    "email": "jocelyn.simpson@nikuda.io",
    "website": "https://nikuda.ca",
    "company": "NIKUDA",
    "name": {
      "last": "Simpson",
      "first": "Jocelyn"
    }
  }
```
I can get address, phone, email, website, and company data, but as soon as I try to display `{name.first}` I get `TypeError: Cannot read property 'first' of undefined`

it gets even more strange because I can get the data by manually looping through with an `Object.keys(data).map()` loop. 

to fully illustrate my issue, here is the full component with the attempts to display the data that dont work, and the one that does is at the bottom, errors are commented in the code.

```jsx
import React, { Component } from 'react';
import PropTypes from 'prop-types';
import {observer} from 'mobx-react';
import { Document } from 'firestorter';

const EventClient = observer(class EventClient extends Component {

  eventClientDoc = new Document(this.props.client); // 

  componentWillReceiveProps(newProps) {
    if (newProps.client !== this.props.client) {
      this.eventClientDoc.path = this.props.client;
    }
  }

  render(){
    const {data, id} = this.eventClientDoc
    const {name, company, phone} = data
    return (
      <div>
        {phone} 
        {name.first /*This returns TypeError: Cannot read property 'first' of undefined*/}
        {
          Object.keys(data.name).map(key => {
            return data.name[key]
          }) // returns error TypeError: Cannot convert undefined or null to object
        }
        {
          Object.keys(data).map(key => {
            return key === 'name'
            ? Object.keys(data[key]).map(i => {
              return <div>{data[key][i]}</div>
            })
            : null
          }) //this one works and returns the first and last names...
        }
      </div>
    );
  }
})

EventClient.propTypes = {
  client: PropTypes.string.isRequired,
}

export default EventClient;
```
any thoughts on why this is happening?

**Comment by IjzerenHein** [comment]
Hi Colin, first of all thanks for the Donation, really appreciate it!

The reason your getting that error, is because on the first render in this example, the data has not yet been fetched from the back-end. Which means that `document.data` returns an empty object. In that case the line `name.first` will throw an error in your code.

You could for instance check whether the document has data, like this:

```
render() {
    const {data, id, snapshot} = this.eventClientDoc
    if (!snapshot) return null; // Document doesn't have any data yet, don't render
    ...
}
```

**Comment by cworf** [comment]
wow, thank you. that did the trick.
Im confused though, isnt that the point of the mobx observable and observer though? to make the component only render when the asynchronous event is ready? I guess observervables are still quite over my head either way, so Ill just stop making assumptions about what they do, haha! 
Many thanks for your help, I have learned quite a bit from this issue :)

**Comment by IjzerenHein** [comment]
Hey Colin. Well, actually no. Observables don't imply anything about asynchronous behaviour. Instead, they are about monitoring changes at a fine-grained level. As in, only re-rendering a component when only the data that it needs has changed.
Your component will always render, even if the data hasn't been fetched yet. And this is actually what you want to happen, because now you can optionally render some state (e.g. a loader) while the data is being retrieved. In most cases the fetch will be pretty fast, but on slow networks you have to deal with the situation that it can take a considerable time and present an appropriate UI to the user for that.

**Comment by IjzerenHein** [comment]
Mind if I close this issue?
