### ISSUE TITLE
React-native not quering collections

### ISSUE THREAD

**Issue by rborn** [IjzerenHein/firestorter#70]
Hi, thanks a lot for this package, it's amazing :)

I'm trying to use the same logic in a ReactJS an ReactNative code but while in web it works fine  in RN it seems that is not executing the queries.

This code will have `docs` empty.
~~~
        this.categoriesCollection = new Collection('categories', { query: ref => ref.orderBy('order', 'asc') });
~~~

I run the "normal" react-native-firebase code and all works as it should.

Any idea? 
Thank you.

**Comment by rborn** [comment]
mmm, maybe is because you don't ever import `observer` from `mobx-react/native` ?

**Comment by rborn** [comment]
ignore me, I'm dumb 🤦‍♂️

**Comment by IjzerenHein** [comment]
No worries :)
