### ISSUE TITLE
Breaking changes in Mobx?

### ISSUE THREAD

**Issue by DennisSchmock** [IjzerenHein/firestorter#8]
Hi. 

Thank you for this great module. I am really enjoying using it in my web-app, saving me a ton of boilerplate. 

But after updating Mobx to the newest version it stopped working for me:

> Failed to compile.
> ./node_modules/firestorter/dist/firestorter.module.js
> 122:12-18 'mobx' does not contain an export named 'extras'.

I have run several test with brand new Create-React-App projects, and the result is the same each time

**From package.json**
firebase": "^4.11.0",
    "firestorter": "^0.9.3",
    "mobx": "^4.1.0",
    "mobx-react": "^5.0.0",

Is it incompatible with Mobx 4?

```import React from 'react'
import {firestoreApp,firebaseApp} from "./db";
import {initFirestorter, Collection} from 'firestorter';
import {observer} from 'mobx-react';

initFirestorter({firebase: firebaseApp}); 

const Tournaments = new Document()

export {Tournaments}

**Comment by daeniz** [comment]
Ok, there is breaking changes in Mobx4/Mobx-react5 when it comes to Firestorter. Just downgraded Mobx to version 3.4.1 and Mobx-react to 4.4.3 and now firestorter works again.

**Comment by IjzerenHein** [comment]
Alright thanks for reporting man! I'll take a look at this shortly, for now please use mobx 3.x
Cheers

**Comment by IjzerenHein** [comment]
Just for my own reference:
https://github.com/mobxjs/mobx/wiki/Migrating-from-mobx-3-to-mobx-4

**Comment by daeniz** [comment]
Well, thank you again for your effort with this plugin. It really rocks.

**Comment by IjzerenHein** [comment]
Hey man, thanks so much for the donation, I really appreciate it!
I'm gonna add you to the list of backers. Cheers dude!

**Comment by IjzerenHein** [comment]
Work in progress, just ran into this issue with mobx 4:
https://github.com/mobxjs/mobx/issues/1437

**Comment by IjzerenHein** [comment]
Hi, I've pushed preliminary support for MobX 4 to the master branch. Still waiting on the previously mentioned issue before I'm gonna release this officially.

**Comment by DennisSchmock** [comment]
Seems like that did the trick. Great work, and I hope the Mobx team picks up your issue fast :-)

**Comment by IjzerenHein** [comment]
Hey Dennis, I've just released an official update that supports MobX 4:
https://github.com/IjzerenHein/firestorter/releases/tag/v0.10.0

Let me know whether I can close this issue?

cheers
