### ISSUE TITLE
react-native-firebase 6.x support

### ISSUE THREAD

**Issue by oOMoeOo** [IjzerenHein/firestorter#84]
Hi,

i just upgraded to react-native 0.61 and react-native-firebase 6.x. Are there any plans to support the new react-native-firebase version with firestorter? They restructured the packages and i wasn't able to embed firestore with initFirestorter. Or am i doing something wrong?

The only way to import firebase from rn-firebase in typescript is: import app from "@react-native-firebase/app". Mapping the app instance into the firestorter init options doesn't work.

Cheers
Moe

**Comment by IjzerenHein** [comment]
Hi!

It should be supported as is. You have to import each package separately though, and then it will be injected in the firebase object. A short while back I tested this and that worked:

```js
import { firebase } from '@react-native-firebase/app';
import '@react-native-firebase/analytics';
import '@react-native-firebase/auth';
import '@react-native-firebase/crashlytics';
import '@react-native-firebase/storage';
import '@react-native-firebase/firestore';
import '@react-native-firebase/dynamic-links';
import '@react-native-firebase/messaging';
import '@react-native-firebase/functions';
// import notifications from '@react-native-firebase/notifications'; // Not supported by v6 yet :(

function async init() {
  ...
  return initFirestorter({
    firebase,
  });
}
```

**Comment by ddikodroid** [comment]
Is it still support the latest version of react native firebase?

**Comment by IjzerenHein** [comment]
As far as I'm aware yes. But if it doesn't please open a issue or PR.
