### ISSUE TITLE
Integrate with firebaseopensource.com

### ISSUE THREAD

**Issue by samtstern** [IjzerenHein/firestorter#85]
Hey @IjzerenHein I'm on the Firebase team and I think your project would be a good addition to https://firebaseopensource.com/

All you'd have to do is add a `.opensource/project.json` file to this repo ([example](https://github.com/FirebaseExtended/flutterfire/blob/master/.opensource/project.json)) and then let me know and I'd be happy to add this project.

**Comment by IjzerenHein** [comment]
Hi @samtstern ! I'd love to see firestorter mentioned there. I will add the file and give you a heads up when it's done.

**Comment by IjzerenHein** [comment]
Hi Sam. I've added the `.opensource/project.json` file to the repo. Let me know if I need to add anything else to it.
Cheers, Hein

**Comment by samtstern** [comment]
@IjzerenHein LGTM!

Added your repo here:
https://github.com/firebase/firebaseopensource.com/commit/0d34522037aee3d35b2667a49bcce29be878275c

You should be on the site within 24 hours, let me know if you have any issues.

**Comment by IjzerenHein** [comment]
Sweet! :D

**Comment by samtstern** [comment]
@IjzerenHein 
https://firebaseopensource.com/projects/ijzerenhein/firestorter/

**Comment by IjzerenHein** [comment]
Sweet!

Page looks good, apart from the badges. @samtstern Do you know what the deal is with the badges, only two are shown. Is the rest filtered out or something?

cheers, Hein

**Comment by samtstern** [comment]
@IjzerenHein we actually try to remove all badges from the rendered pages (in the top section at least) so from our perspective the bug is the two that remain rather than the ones that are missing.

**Comment by IjzerenHein** [comment]
@samtstern Ah I see. I kinda figured something like that. Is there something I can do in the Firestorter README.md to assist in that?

**Comment by samtstern** [comment]
@IjzerenHein I believe this commit will remove the last two badges:
https://github.com/firebase/firebaseopensource.com/commit/9ed3aa89dd13814ef6e753410b84d64be6157b3e

In the end it's just a blacklist.  Like any blacklist, it's always missing things.

**Comment by IjzerenHein** [comment]
Hehe, and so is the nature of such things :)

I checked, and it all looks now 👍 

Thanks for listing this on firebaseopensource.

cheers, Hein
