### ISSUE TITLE
missing links?

### ISSUE THREAD

**Issue by thirdman** [IjzerenHein/firestorter#86]
I possibly caught it on the day you're updating it, but just want to note that the links at the bottom of the readme don't appear to work anymore.

I'm guessing this....

"Add, update & delete documents:  "
needs to point to: https://ijzerenhein.github.io/firestorter/#/./guides/AddUpdateDelete
instead of: https://firestorter.com/guides/AddUpdateDelete.md

Love your work! 😍

**Comment by IjzerenHein** [comment]
Haha, yes you're right 😅
I'm in the process of publishing an all new Documentation website and Firestorter v2.
Thanks for letting me know, will fix :)
Btw, all the docs  can now be accessed through firestorter.com
cheers!

**Comment by IjzerenHein** [comment]
Alright it's fixed now!
cheers!
