### ISSUE TITLE
Collection.query is not working

### ISSUE THREAD

**Issue by gsouf** [IjzerenHein/firestorter#93]
Hello,

I have issues using the query option/method of the the collection.

It's not evaluated at all.

The example bellow won't take into account my "limit=3"

```
import { observer } from 'mobx-react';
@observer
export default class StockHistoryScreen extends React.Component {
  constructor(props) {
    super(props);
    this.collection = new Collection('mycollection', {
      query: ref => {
        ref.limit(3);
      }
    });
  }

  render() {
    const { navigate } = this.props.navigation;

    return (
      <View>
        {this.collection.docs.map(doc => {
          return <View>{doc.id}</View>;
        })}
      </View>
    );
```

**Comment by IjzerenHein** [comment]
Hi! There seems to be an error in your code.

```js
query: ref => {
        ref.limit(3);
      }
```

should be:

```js
query: ref => {
        return ref.limit(3);
      }
```

or 

```js
query: ref => ref.limit(3)
```

**Comment by gsouf** [comment]
@IjzerenHein thanks for your input but I confirm it does not work, the function passed in the param `query` is not called at all.

**Comment by IjzerenHein** [comment]
Hmm that is strange indeed. Are you getting any docs at all?

**Comment by gsouf** [comment]
I'm getting all docs in the collection, like if I didn't specify any query. As I said it's not evaluated at all. So the same occurs with `where` or `orderBy`. Missing something obvious?

**Comment by IjzerenHein** [comment]
That is so weird.. The `query` arg is a critical part of Firestorter, without it you couldn't do any kind of query's, so it's hard to believe it's broken. Can you perhaps share a small sample app on codesandbox/stackblitz that shows the problem?

**Comment by gsouf** [comment]
found the issue, was related to some tools out of the scope of firestorter sorry for the mess
