### ISSUE TITLE
Trigger listener on get

### ISSUE THREAD

**Issue by RWOverdijk** [IjzerenHein/firestorter#98]
Where `products` is a `Collection` Is there a way to prevent having to do something like this:

```js
products.docs.map(x => x)[0]?.data
```

And instead just allow this:

```js
products.docs[0]?.data
```

Unless I map, the data never gets retrieved. It seems to me that this _could_ be done because it's also possible to Proxy arrays, I just think I don't understand this library very well. 😄

**Comment by IjzerenHein** [comment]
Hmm, good one.  I guess you would need have a write some kind of helper function for that. Perhaps something like this?

```js
function getFirstDoc(col: Collection) {
  return products.length ? products.slice(0)[0] : undefined;
}
```

As for the `docs[0]` construct, I would have expected that to work tbh. Not sure why that doesn't create a MobX reaction, might be a problem with the MobX proxy indeed, or TypeScript might convert it to an unexpected JS construct.

**Comment by RWOverdijk** [comment]
@IjzerenHein If you mean typescript on my end, I am sad to say I'm not using typescript (but only because expo init doesn't do what I need right now).

As to the helper, that'd be fine. I can do that.

So what if I need one document's id to find documents from another collection? Practical example:

I have venues. Venues need to be looked up by slug:

```js
{
    query: (ref) => ref.where('slug', '==', slug).limit(1)
  }
```

Then I need to use the document ID to find something else in a constructor, like orders:

`order/${user.uid}/venue/${venueID}/product`

But I do want to maintain the live updates (otherwise I'd simply use .fetch and turn off auto updates).

Right now I'm doing this:

```js
const venue = await findBySlug(this.props.route.params.slug)
const orders = await findOrders(venue.id)
```

Which doesn't feel ideal.
